Fixed UnpackerConfig.bufferSize to work
msgpack/msgpack-java pull request #658
Opened 2022-06-22 15:20 UTC by napo0703

This will Resolve #657

It limits internal buffer size when unpacking Array and Map.
However, I think the default bufferSize of 8192 is too small.
I changed the default buffer size to 100MiB following [msgpack-python](https://github.com/msgpack/msgpack-python#security).

2022-06-28 07:07 UTC, xerial commented on msgpack-core/src/main/java/org/msgpack/core/MessagePack.java
> +        private int bufferSize = 100 * 1024 * 1024;
Don't change the default buffer size. msgpack-java is frequently used even for the small size of data.

2022-06-28 07:10 UTC, xerial commented on msgpack-core/src/main/java/org/msgpack/core/MessagePack.java
> +        private int bufferSize = 100 * 1024 * 1024;
Especially, creating a large buffer is not free as Java will use CPU resources for filling zeros to the array contents.

2022-06-28 07:18 UTC, xerial requested changes
- Do not change the default buffer size from 8K
- Setting the default buffer size from config is ok
- Do not throw an exception in unpackXXXheader. Only readPayload needs to be fixed to support large volumes of data
- readPayload should swap the existing buffer to a large buffer if the payload length exceeds the current bufferSize

2022-06-28 07:19 UTC, xerial commented on msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
> +        return len;
Throwing error here is unnecessary if readPayload checks the buffer size.

2022-06-28 07:20 UTC, xerial commented on msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
> +        return len;
Unnecessary change for the same reason

2022-06-28 17:38 UTC, napo0703 commented on msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
> +        if (length > bufferSize) {
I'm sorry that I don't quite understand here.
Am I correct that the purpose of `UnpackerConfig.bufferSize` is to limit the size of the new byte array in `readPayload(int)`?
Do I need to change this code?

2022-06-29 15:03 UTC, napo0703 commented
Buffer size limits now work, but some tests no longer pass.
Should I change the Unpacker buffer size used for this test in the settings?
```
-        val unpacker = MessagePack.newDefaultUnpacker(new InputStreamBufferInput(new ByteArrayInputStream(out.toByteArray)))
+        val unpacker = new MessagePack.UnpackerConfig().withBufferSize(16 * 1024).newUnpacker(new InputStreamBufferInput(new ByteArrayInputStream(out.toByteArray)))
```

2023-09-24 04:23 UTC, xerial commented
Upon re-reading the PR, I noticed some misunderstandings.

UnpackerConfig.bufferSize is used to control the internal buffer size, but it is not meant to limit the size of the input uncompressed data. In order to prevent loading excessively large data into memory, we need to introduce another configuration. 

I will close this pull request because it has become outdated. The requirement to limit the uncompressed data size and fail the Unpacker is still valid, but it should be addressed in a different context.

2023-09-24 04:23 UTC, closed without merging